### ISSUE TITLE
Feature request: additional filtering and batch downloads

### ISSUE THREAD

**Issue by koopa1338** [Beastwick18/nyaa#10]
I like the client so far, but these feature would be really nice to add:

- filters for subbing group and video quality/resolution
- adding multiple torrent links at once by having a _visual mode_ or tag them with spacebar (kind of what the yazi tui file browser is doing for selecting files)

**Comment by Beastwick18** [comment]
> filters for subbing group and video quality/resolution

This is a good idea. Should definitely be possible to add by the next release. The way it would likely work is it would be a separate popup with in an input box to put the "user" you want to 
search for. This would be translated to the `u=...` parameter in the URL.

As for resolution, on nyaa I don't believe there is any official way to search for just that. Because of that, I likely wont be able to add a seperate filter, since all it could do is append the quality "filter" onto the end of the search query. So `Search: one punch man | Quality: 1080p` would just become `Search: one punch man 1080p`.

> adding multiple torrent links at once by having a visual mode or tag them with spacebar (kind of what the yazi tui file browser is doing for selecting files)

This is something that would be great to have. Looking at yazi, the way they've done it looks really clean. I very likely will do something very similar, since my previous idea on how to add it would be adding an entire new column for indicating an item is "selected". It will likely also use the spacebar, as that seems intuitive and what most users will expect.

Thanks for the suggestions! :)

**Comment by Beastwick18** [comment]
Got something working. Here's a demo:
![demo](https://github.com/Beastwick18/nyaa/assets/13501575/eb07347f-daa4-461d-a4f3-8df1052c30ba)

This is only visual for now, actual batch downloading will require some reworking. This should be a feature by the next release.

Feel free to leave suggestions for further improvements.

**Comment by Beastwick18** [comment]
Closing as now batch downloading (8a3e5cd) and filtering by user (65f33ac) are added on main branch, and quality filters are not planned.
