### ISSUE TITLE
Tests gets stuck

### ISSUE THREAD

**Issue by Amatrelan** [Beastwick18/nyaa#16]
When running tests it seems to get stuck, not exactly sure why.
```shell
     Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/nyaa-3af1009498ee980a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/nyaa-0cf8c002ae8ac6c6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/input.rs (target/debug/deps/input-cedcbeea865cc100)

running 1 test
test test_search has been running for over 60 seconds
```

and it doesn't seems to go forward at all.

And one other thing about those tests, it might be that those wouldn't even work on my machine because I have custom `default_search` so it would modify buffer on that case.

I tried without custom config but still stuck on tests.

**Comment by Beastwick18** [comment]
Strange... which command are you using to start the tests? They're kind of non-standard since they use shared memory through a Mutex. Rust tests are by default run multithreaded, and this memory could be changed by another test, so it must be run single threaded. Just `cargo test` will usually fail. The tests also enable a feature to disable parts of the code that load the users config so the tests work independent of the users setup.

In the repo, there should be an alias to run them, which is
```
cargo integration-test
```
which maps to
```
cargo test --features integration-test -- --test-threads=1
```

Thinking about it now, I should probably resort to less hacky solutions 😅. I might rewrite them soon in a way that would be more expected.

**Comment by Beastwick18** [comment]
72af9d2 should address this. Now, `cargo test` should just work.

**Comment by Amatrelan** [comment]
Yeah I noticed this problem because I use NixOS and installed through nix this, and it usually just run by default `cargo test` when installing if you don't configure it on flake what you provide how to run tests. 

> The tests also enable a feature to disable parts of the code that load the users config so the tests work independent of the users setup.

Ah didn't notice this part on quick glance so my bad.

But now this seems to work just fine so you can close this issue if you want to.
